"""create base tables

Revision ID: 59bc6f5571ec
Revises: 
Create Date: 2025-11-18 16:51:14.712205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59bc6f5571ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('trigger_message_id', sa.UUID(), nullable=True),
    sa.Column('response_message_id', sa.UUID(), nullable=True),
    sa.Column('fragment_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chronos_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='forecaststatus'), nullable=False),
    sa.Column('requested_horizon', sa.Integer(), nullable=True),
    sa.Column('device', sa.String(length=32), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=32), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('point_forecast', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quantiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['forecast_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'TOOL', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence_index', name='uq_messages_sequence')
    )
    op.create_table('upload_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('extraction_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='extractionstatus'), nullable=False),
    sa.Column('extraction_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_artifacts')
    op.drop_table('messages')
    op.drop_table('forecast_series')
    op.drop_table('forecast_jobs')
    op.drop_table('conversation_sessions')
    sa.Enum('USER', 'ASSISTANT', 'TOOL', name='messagerole').drop(op.get_bind(), checkfirst=False)
    sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', name='extractionstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='forecaststatus').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
